### ISSUE TITLE
On Windows, doc-strings can include paths with backslashes without escaping

### ISSUE THREAD

**Issue by alexpolozov** [lukaslueg/built#35]
On a Windows machine, `RUSTC_VERSION` could appear as:
``` rust
#[doc="The output of `C:\Users\username\.cargo\bin\rustc.exe -V`"]
#[allow(dead_code)]
pub const RUSTC_VERSION: &str = r"rustc 1.50.0 (cb75ad5db 2021-02-10)";
```
which obviously breaks the build. One simple fix would be to generate all docs in `write_variable!` as raw strings. But I'm not sure if it could break anything else, so not submitting a PR just yet.

**Comment by lukaslueg** [comment]
Thanks for the report. The issue was fixed in aa5362a17bfa5e774d1a795204aa4aab995bf6f4, which is not yet released. I guess I'll bump to 0.5 soon to get the fix out the door.

**Comment by alexpolozov** [comment]
@lukaslueg It's not actually fixed, I'm observing this error on master, not in the released build.
The `write_variable!` macro emits the doc verbatim as `"#[doc=\"{}\"]\npub const {}: {} = {};"`, which inlines the string like I described. It should be `"#[doc=r\"{}\"]\npub const {}: {} = {};"`.

**Comment by lukaslueg** [comment]
I'm still wondering why this and #27 hasn't been picked up before, at least during CI

**Comment by alexpolozov** [comment]
Good question. From my cursory look, that depends on how Rust was installed. On the CI machine, the environment variable RUSTC is probably equal to `rustc`, which is in the PATH. On my machine, RUSTC for some reason stores the absolute path to `rustc` (even though it's in the PATH as well).
Windows has several ways to install software (Chocolatey, winget, dedicated installers, etc.), they might initialize environment variables differently.

**Comment by lukaslueg** [comment]
yeah, figured that. I'll add a test.

**Comment by lukaslueg** [comment]
Should be fixed in latest master

**Comment by lukaslueg** [comment]
@alexpolozov This is now fixed in 55f4de3931a2f99ce726e1a1bc4aa66d443bc519, please re-open if you still run into problems.

**Comment by alexpolozov** [comment]
Thank you, @lukaslueg!
